name: 'Sub-split Publish'
description: 'Publish git repository sub-splits using splish-lite'

inputs:
    config-path:
        required: true
        description: 'Path for sub-split config'
    splitsh-version:
        default: v1.0.1
        description: 'Version of splitsh to install'
        required: false
    splitsh-path:
        description: 'Path to install splitsh-lite'
        required: true
    origin-remote:
        description: 'Name of the origin remote'
        default: 'origin'
        required: false
    max-tries:
        description: 'Amount of retries per call that can fail (splish/git)'
        default: '5'
        required: false
    source-branch:
        description: 'Branch to split from'
        required: true
branding:
    icon: external-link
    color: purple
runs:
    using: 'node20'
    main: 'dist/index.js'
