name: Sub-split Publishing
on:
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'
  push:
    paths:
      - '.github/workflows/**/*'
      - 'dist/**/*'
      - 'action.yml'
    branches:
      - main
      - feature/configure-destination-branch

jobs:
  publish_sub_splits:
    runs-on: ubuntu-latest
    name: Publish Sub-split
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'frankdejonge:${{ secrets.PERSONAL_GITHUB_TOKEN }}'
          user_name: 'Frank de Jonge'
          user_email: 'info@frenky.net'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v3
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh-d-101'
      - uses: ./
        with:
          source-branch: 'main'
          config-path: './config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
